In [1]:
import pandas as pd

## 1. Extraction

In [2]:
# load dataset
df = pd.read_csv("../data/motor-vehicle-collisions.csv")
df.head()

,_id,collision_id,accdate,stname1,stname2,stname3,per_inv,acclass,accloc,traffictl,...,distracted,cyclist,motorcyclist,other_micromobility,older_adult,pedestrian,red_light,school_child,heavy_truck,geometry
0,1,2006:893184,2006-01-01T02:36:00,WOODBINE AVE,O CONNOR DR,NaN,8,Non-Fatal Injury,Intersection-Related,No Control,...,False,False,False,False,False,False,False,True,False,"{""coordinates"": [[-79.31879768423914, 43.69959..."
1,2,2006:893184,2006-01-01T02:36:00,WOODBINE AVE,O CONNOR DR,NaN,8,Non-Fatal Injury,Intersection-Related,No Control,...,False,False,False,False,False,False,False,True,False,"{""coordinates"": [[-79.31879768423914, 43.69959..."
2,3,2006:893184,2006-01-01T02:36:00,WOODBINE AVE,O CONNOR DR,NaN,8,Non-Fatal Injury,Intersection-Related,No Control,...,False,False,False,False,False,False,False,True,False,"{""coordinates"": [[-79.31879768423914, 43.69959..."
3,4,2006:893184,2006-01-01T02:36:00,WOODBINE AVE,O CONNOR DR,NaN,8,Non-Fatal Injury,Intersection-Related,No Control,...,False,False,False,False,False,False,False,True,False,"{""coordinates"": [[-79.31879768423914, 43.69959..."
4,5,2006:893184,2006-01-01T02:36:00,WOODBINE AVE,O CONNOR DR,NaN,8,Non-Fatal Injury,Intersection-Related,No Control,...,False,False,False,False,False,False,False,True,False,"{""coordinates"": [[-79.31879768423914, 43.69959..."

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20631 entries, 0 to 20630
Data columns (total 50 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   _id                  20631 non-null  int64
 1   collision_id         20631 non-null  str
 2   accdate              20631 non-null  str
 3   stname1              20631 non-null  str
 4   stname2              18858 non-null  str
 5   stname3              4763 non-null   str
 6   per_inv              20631 non-null  int64
 7   acclass              20630 non-null  str
 8   accloc               15176 non-null  str
 9   traffictl            20384 non-null  str
 10  impactype            20600 non-null  str
 11  visible              20570 non-null  str
 12  light                20590 non-null  str
 13  rdsfcond             20560 non-null  str
 14  road_class           19869 non-null  str
 15  failtorem            20631 non-null  bool
 16  longitude            20628 non-null  float64
 17  latitude             20628 non-null  float64
 18  veh_no               20132 non-null  float64
 19  vehtype              11815 non-null  str
 20  initdir              14811 non-null  str
 21  per_no               20630 non-null  float64
 22  invage               18007 non-null  float64
 23  injury               10980 non-null  str
 24  safequip             19186 non-null  str
 25  drivact              10581 non-null  str
 26  drivcond             10622 non-null  str
 27  pedact               3557 non-null   str
 28  pedcond              3587 non-null   str
 29  manoeuvre            12017 non-null  str
 30  pedtype              3550 non-null   str
 31  cyclistype           886 non-null    str
 32  cycact               885 non-null    str
 33  cyccond              885 non-null    str
 34  road_user            20631 non-null  str
 35  fatal_no             1094 non-null   float64
 36  wardname             20509 non-null  str
 37  division             20565 non-null  str
 38  neighbourhood        20480 non-null  str
 39  aggressive           20631 non-null  bool
 40  distracted           20631 non-null  bool
 41  cyclist              20631 non-null  bool
 42  motorcyclist         20631 non-null  bool
 43  other_micromobility  20631 non-null  bool
 44  older_adult          20631 non-null  bool
 45  pedestrian           20631 non-null  bool
 46  red_light            20631 non-null  bool
 47  school_child         20631 non-null  bool
 48  heavy_truck          20631 non-null  bool
 49  geometry             20628 non-null  str
dtypes: bool(11), float64(6), int64(2), str(31)
memory usage: 6.4 MB

In [4]:
# check null or missing values
df.isnull().sum()

_id                        0
collision_id               0
accdate                    0
stname1                    0
stname2                 1773
stname3                15868
per_inv                    0
acclass                    1
accloc                  5455
traffictl                247
impactype                 31
visible                   61
light                     41
rdsfcond                  71
road_class               762
failtorem                  0
longitude                  3
latitude                   3
veh_no                   499
vehtype                 8816
initdir                 5820
per_no                     1
invage                  2624
injury                  9651
safequip                1445
drivact                10050
drivcond               10009
pedact                 17074
pedcond                17044
manoeuvre               8614
pedtype                17081
cyclistype             19745
cycact                 19746
cyccond                19746
road_user                  0
fatal_no               19537
wardname                 122
division                  66
neighbourhood            151
aggressive                 0
distracted                 0
cyclist                    0
motorcyclist               0
other_micromobility        0
older_adult                0
pedestrian                 0
red_light                  0
school_child               0
heavy_truck                0
geometry                   3
dtype: int64

In [5]:
# check duplicate values
df.duplicated().sum()

np.int64(0)

## 2. Transform

In [6]:
# create a collision table to store information related to the collision
collision_columns = ["collision_id",
                     "accdate",
                     "stname1",
                     "stname2",
                     "stname3",
                     "per_inv",
                     "acclass",
                     "accloc",
                     "traffictl",
                     "impactype",
                     "visible",
                     "light",
                     "rdsfcond",
                     "road_class",
                     "failtorem",
                     "longitude",
                     "latitude",
                     "wardname",
                     "division",
                     "neighbourhood",
                     "aggressive",
                     "distracted",
                     "cyclist",
                     "motorcyclist",
                     "other_micromobility",
                     "older_adult",
                     "pedestrian",
                     "red_light",
                     "school_child",
                     "heavy_truck"]

collision_df = (df[collision_columns].drop_duplicates())

In [7]:
collision_df.head()

,collision_id,accdate,stname1,stname2,stname3,per_inv,acclass,accloc,traffictl,impactype,...,aggressive,distracted,cyclist,motorcyclist,other_micromobility,older_adult,pedestrian,red_light,school_child,heavy_truck
0,2006:893184,2006-01-01T02:36:00,WOODBINE AVE,O CONNOR DR,NaN,8,Non-Fatal Injury,Intersection-Related,No Control,Approaching Head On,...,False,False,False,False,False,False,False,False,True,False
8,2006:909646,2006-01-01T03:15:00,DANFORTH AVE,WEST LYNN AVE,NaN,5,Non-Fatal Injury,Intersection-Related,No Control,SMV Other,...,False,True,False,False,False,False,False,False,True,False
13,2006:884090,2006-01-02T07:05:00,BATHURST ST,DUNDAS ST W,60 NORTH OF,2,Non-Fatal Injury,NaN,No Control,Pedestrian Collision(internal code),...,False,True,False,False,False,False,True,False,False,False
15,2006:885782,2006-01-04T19:40:00,DUFFERIN ST,SYLVAN AVE,NaN,2,Non-Fatal Injury,At Intersection,Traffic Signal,Pedestrian Collision(internal code),...,False,False,False,False,False,True,True,False,False,False
17,2006:882079,2006-01-06T22:10:00,DON MILLS RD,LEITH HILL RD,NaN,2,Non-Fatal Injury,At Intersection,Traffic Signal,Pedestrian Collision(internal code),...,False,True,False,False,False,False,True,False,False,False

In [8]:
collision_df.shape

(7564, 30)

In [9]:
# create a person table that stores information about
# each person involved in each collision
person_columns = ["collision_id",
                  "per_no",
                  "veh_no",
                  "vehtype",
                  "initdir",
                  "road_user",
                  "invage",
                  "injury",
                  "safequip",
                  "drivact",
                  "drivcond",
                  "pedact",
                  "pedcond",
                  "manoeuvre",
                  "pedtype",
                  "cyclistype",
                  "cycact",
                  "cyccond",
                  "fatal_no"]

person_df = df[person_columns].copy()

# add person_id column
person_df.insert(0, "persion_id", range(1, len(person_df)+1))

person_df.head()

,persion_id,collision_id,per_no,veh_no,vehtype,initdir,road_user,invage,injury,safequip,drivact,drivcond,pedact,pedcond,manoeuvre,pedtype,cyclistype,cycact,cyccond,fatal_no
0,1,2006:893184,4.0,2.0,NaN,NaN,passenger,19.0,Minor,Equipment Not Used But Available,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2006:893184,2.0,1.0,Automobile or Station Wagon,North,driver,55.0,Minor,Lap and Shoulder Belt,Driving properly,Normal,NaN,NaN,Going Ahead,NaN,NaN,NaN,NaN,NaN
2,3,2006:893184,3.0,2.0,NaN,NaN,passenger,20.0,Minor,Equipment Not Used But Available,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,2006:893184,6.0,1.0,NaN,NaN,passenger,51.0,Major,Lap and Shoulder Belt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,2006:893184,1.0,1.0,NaN,NaN,passenger,17.0,Minor,Lap and Shoulder Belt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
person_df.shape

(20631, 20)

## 3. Load

In [11]:
import os
from dotenv import load_dotenv

load_dotenv()

True

In [12]:
# read credentials
from urllib.parse import quote_plus
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = quote_plus(os.getenv("DB_PASSWORD"))
DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")
DB_NAME = os.getenv("DB_NAME")

In [13]:
# connect to postgres
from sqlalchemy import create_engine, text
engine = create_engine(f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}")

In [14]:
# create schema
with open("../databases/schema.sql", "r") as file:
    sql_script = file.read()
with engine.begin() as conn:
    conn.execute(text(sql_script))

In [15]:
# load collision table into postgres
collision_df.to_sql("collision", 
          engine, 
          if_exists="append",
          index=False,
          chunksize=20000,
          method="multi")

7564

In [16]:
# load person table into postgres
person_df.to_sql("person", 
          engine, 
          if_exists="replace",
          index=False,
          chunksize=20000,
          method="multi")

20631